Add error handling when antigen failed to install
Signed-off-by: Jun Zhang <jun@junz.org>

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -37,23 +37,29 @@ for dir in $(ls ~/opt); do
 done
 
 export PATH=$PATH:~/dev/depot_tools
-if [ ! -d $ANTIGEN_HOME ]; then
+
+if [ ! -d ${ANTIGEN_HOME} ]; then
     echo "antigen is not available, install it now..."
-    mkdir ~/.antigen
-    curl -L git.io/antigen > ~/.antigen/antigen.zsh
+    mkdir ${ANTIGEN_HOME}
+    curl -sL git.io/antigen > ${ANTIGEN_HOME}/antigen.zsh
 fi
 
-source ~/.antigen/antigen.zsh
-
-antigen use oh-my-zsh
-antigen bundle vi-mode
-antigen bundle git
-antigen bundle fzf
-antigen bundle zsh-users/zsh-autosuggestions
-antigen bundle zsh-users/zsh-syntax-highlighting
-antigen bundle romkatv/powerlevel10k
-antigen theme romkatv/powerlevel10k
-antigen apply
+if [[ $(cat ${ANTIGEN_HOME}/antigen.zsh | wc -l) == 0 ]]; then
+    echo "antigen failed to install!"
+    rm -rf ${ANTIGEN_HOME}
+    exit 1
+else
+    source ${ANTIGEN_HOME}/antigen.zsh
+    antigen use oh-my-zsh
+    antigen bundle vi-mode
+    antigen bundle git
+    antigen bundle fzf
+    antigen bundle zsh-users/zsh-autosuggestions
+    antigen bundle zsh-users/zsh-syntax-highlighting
+    antigen bundle romkatv/powerlevel10k
+    antigen theme romkatv/powerlevel10k
+    antigen apply
+fi
 
 function work {
     if [[ -n "$TMUX" ]]
